use CutePuppiesTest;

ALTER TABLE Content MODIFY COLUMN CreatedOnDate DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Content MODIFY COLUMN UpdatedOnDate DATETIME ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE Content MODIFY COLUMN ArchivedOnDate datetime;

ALTER TABLE Post MODIFY COLUMN CreatedOnDate DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Post MODIFY COLUMN UpdatedOnDate DATETIME ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE Post MODIFY COLUMN ArchivedOnDate datetime;

ALTER TABLE `User` MODIFY COLUMN CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `User` MODIFY COLUMN UpdatedDate DATETIME ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `User` MODIFY COLUMN DeletedDate datetime;